"""Evaluate ResNet on pre-computed DroneRFa features.

Usage:
  python scripts/evaluate.py --feature stft --data-dir ~/Desktop/dataset/droneRFa/stft_h5 --model-path outputs/checkpoints/best_stft_model.pth --split-manifest outputs/splits/random12_seed42.csv
  python scripts/evaluate.py --feature cpp --data-dir ~/Desktop/dataset/droneRFa/cpp_h5 --model resnet18-small-stem --model-path outputs/checkpoints/best_cpp_model.pth --split-manifest outputs/splits/random12_seed42.csv

"""

import argparse
import os
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import confusion_matrix
from torch.utils.data import DataLoader

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.data.splits import load_test_subset
from src.data.class_filter import RemappedSubset, add_exclusion_suffix, build_class_mapping
from src.models.resnet import NUM_CLASSES, build_model
from src.training.checkpoint import load_checkpoint
from src.training.evaluator import evaluate_with_predictions
from src.training.metrics import compute_metrics, save_confusion_matrix_image

from src.utils.cli import log_current_command
from src.utils.device import default_device
from src.utils.feature_specs import get_feature_spec
from src.utils.logger import logger
from src.utils.paths import figures_dir, metrics_dir

BATCH_SIZE = 64
DEFAULT_MODEL_BY_FEATURE = {
    "stft": "resnet18",
    "cpp": "resnet18-small-stem",
}


def build_parser():
    parser = argparse.ArgumentParser(description="Evaluate ResNet on pre-computed DroneRFa features")
    parser.add_argument("--feature", type=str, default="stft", choices=("stft", "cpp"))
    parser.add_argument("--model", type=str, default=None, choices=("resnet18", "resnet18-small-stem"),
                        help="Model architecture (default: resnet18 for STFT, resnet18-small-stem for CPP)")
    parser.add_argument("--data-dir", type=str, default=None, help="Directory containing feature .h5 files")
    parser.add_argument("--model-path", type=str, default=None, help="Path to model checkpoint")
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--num-workers", type=int, default=0,
                        help="DataLoader workers (0 = main process only)")
    parser.add_argument("--device", type=str, default=default_device(),
                        help="Device, e.g. 'cuda:0', 'cuda:1', 'mps', 'cpu'")
    parser.add_argument("--cm-image-path", type=str, default=None, help="Path to save confusion matrix image")
    parser.add_argument("--split-manifest", type=str, required=True,
                        help="Existing CSV manifest generated by scripts/train.py")
    parser.add_argument("--exclude-labels", type=int, nargs="*", default=None,
                        help="Original class labels excluded during training")
    return parser


def parse_args(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)

    spec = get_feature_spec(args.feature)
    args.model = args.model if args.model is not None else DEFAULT_MODEL_BY_FEATURE[args.feature]
    args.data_dir = os.path.expanduser(args.data_dir) if args.data_dir is not None else spec.default_data_dir
    args.model_path = (
        os.path.expanduser(args.model_path)
        if args.model_path is not None
        else add_exclusion_suffix(spec.checkpoint_name, args.exclude_labels)
    )
    args.cm_image_path = (
        os.path.expanduser(args.cm_image_path)
        if args.cm_image_path is not None
        else add_exclusion_suffix(figures_dir() / spec.cm_image_name, args.exclude_labels)
    )
    args.split_manifest = os.path.expanduser(args.split_manifest)
    return args


def evaluate(args):
    spec = get_feature_spec(args.feature)
    if not Path(args.split_manifest).is_file():
        raise FileNotFoundError(f"Split manifest does not exist: {args.split_manifest}")
    device = torch.device(args.device)
    if device.type == "cuda":
        torch.cuda.set_device(device)

    logger.info("Using device: %s", device)
    if device.type == "cuda":
        logger.info("GPU: %s", torch.cuda.get_device_name(0))

    dataset = spec.dataset_class(args.data_dir)
    try:
        logger.info("Loaded %d %s samples from %d .h5 files in %s",
                    len(dataset), spec.name, len(set(s[0] for s in dataset.index)), args.data_dir)

        test_ds = load_test_subset(
            dataset,
            manifest_path=args.split_manifest,
        )
        mapping = build_class_mapping(NUM_CLASSES, args.exclude_labels)
        test_ds = RemappedSubset(test_ds, mapping)
        logger.info("Class mapping (model -> original): %s", mapping.original_labels)
        test_file_count = len({dataset.index[index][0] for index in test_ds.indices})
        logger.info(
            "Loaded test split from %s: %d files, %d samples",
            args.split_manifest,
            test_file_count,
            len(test_ds),
        )

        loader_kwargs = dict(
            batch_size=args.batch_size,
            num_workers=args.num_workers,
            pin_memory=(device.type == "cuda"),
        )
        if args.num_workers > 0:
            loader_kwargs["prefetch_factor"] = 4
            loader_kwargs["persistent_workers"] = True

        test_loader = DataLoader(test_ds, **loader_kwargs)

        model = build_model(args.model, num_classes=mapping.num_classes).to(device)
        logger.info("Loading model from %s", args.model_path)
        state_dict = load_checkpoint(args.model_path, map_location=device)
        model.load_state_dict(state_dict)

        criterion = nn.CrossEntropyLoss()
        test_loss, _test_acc, preds, labels = evaluate_with_predictions(
            model, test_loader, criterion, device
        )

        metrics = compute_metrics(preds, labels)
        logger.info("=" * 55)
        logger.info("%s Test Results:", spec.name.upper())
        logger.info("  Accuracy:  %.4f", metrics["accuracy"])
        logger.info("  Precision: %.4f", metrics["precision"])
        logger.info("  Recall:    %.4f", metrics["recall"])
        logger.info("  F1-Score:  %.4f", metrics["f1"])
        logger.info("  Test Loss: %.4f", test_loss)
        logger.info("=" * 55)

        cm = confusion_matrix(labels, preds, labels=range(mapping.num_classes))
        metric_path = metrics_dir()
        os.makedirs(metric_path, exist_ok=True)
        cm_path = Path(add_exclusion_suffix(metric_path / spec.cm_array_name, args.exclude_labels))
        np.save(cm_path, cm)
        logger.info("Confusion matrix saved to %s", cm_path)

        cm_image_path = Path(args.cm_image_path)
        os.makedirs(cm_image_path.parent, exist_ok=True)
        save_confusion_matrix_image(cm, cm_image_path, class_labels=mapping.original_labels)
        logger.info("Confusion matrix image saved to %s", cm_image_path)
        return metrics
    finally:
        dataset.close()


def main():
    args = parse_args()
    log_current_command(logger)
    evaluate(args)


if __name__ == "__main__":
    main()
